volumes:
  data:
    external: false

services:
  app:
    image: wordpress
    container_name: wordpress_app
    volumes:
      - data:/var/www/html
      - ./src:/var/www/html/wp-content
    depends_on:
      db:
        condition: service_healthy
      cli:
        condition: service_completed_successfully
    restart: always
    ports:
      - "3000:80"

  db:
    image: mariadb
    container_name: wordpress_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

  cli:
    image: wordpress:cli
    volumes:
      - ./init.sh:/init.sh
      - data:/var/www/html
    entrypoint: ["sh", "-c", "/init.sh"]
    depends_on:
      db:
        condition: service_healthy
