volumes:
  data:
    external: false

services:
  app:
    build: ./.docker
    container_name: wordpress_app
    volumes:
      - data:/var/www/html
      - ./src:/var/www/html/wp-content/themes/example
    depends_on:
      db:
        condition: service_healthy
      cli-init:
        condition: service_completed_successfully
    ports:
      - "${WP_PORT}:80"

  db:
    image: mariadb
    container_name: wordpress_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
      start_interval: 3s

  cli-init:
    image: wordpress:cli
    container_name: wordpress_cli_init
    volumes:
      - ./init.sh:/init.sh
      - data:/var/www/html
    environment:
      - DB_PASSWORD
      - DB_NAME
      - DB_PREFIX
      - WP_USER
      - WP_PASSWORD
      - WP_PORT
    entrypoint: ["sh", "-c", "/init.sh"]
    depends_on:
      db:
        condition: service_healthy

  cli-post:
    image: wordpress:cli
    container_name: wordpress_cli_post
    volumes:
      - data:/var/www/html
      - ./src:/var/www/html/wp-content/themes/example
    entrypoint: ["wp", "theme", "activate", "example"]
    depends_on:
      - app