volumes:
  data:
    external: false

services:
  app:
    image: wordpress
    volumes:
      - data:/var/www/html
      - ./src:/var/www/html/wp-content
    depends_on:
      db:
        condition: service_healthy
      cli:
        condition: service_completed_successfully
    restart: always
    ports:
      - "3000:80"

  db:
    image: mariadb
    container_name: ${DB_HOST}
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

  cli:
    image: wordpress:cli
    volumes:
      - ./init.sh:/init.sh
      - data:/var/www/html
    environment:
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - DB_PREFIX
      - DB_HOST
      - WP_USER
      - WP_PASSWORD
    entrypoint: ["sh", "-c", "/init.sh"]
    depends_on:
      db:
        condition: service_healthy
